In [ ]:
from google.colab import drive
drive.mount ('/content/drive')

Mounted at /content/drive


In [ ]:
L = list(range(10))
L 

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

A Python List Is More Than Just a List 


In [ ]:
 type(L[0]) 

int

In [ ]:
 L2 = [str(c) for c in L]
L2 

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

#LISTS IN PYTHON


In [ ]:
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3] 

[bool, str, float, int]

Because of Python’s dynamic typing, we can even create heterogeneous 

But this flexibility comes at a cost: to allow these flexible types, each item in the list must contain its own type info, reference count, and other information—that is, each item is a complete Python object. In the special case that all variables are of the same type, much of this information is redundant: it can be much more efficient to store data in a fixed-type array. The difference between a dynamic-type list and a fixed-type (NumPy-style) array is illustrated in Figure 2-2. At the implementation level, the array essentially contains a single pointer to one con‐ tiguous block of data. The Python list, on the other hand, contains a pointer to a block of pointers, each of which in turn points to a full Python object like the Python integer we saw earlier. Again, the advantage of the list is flexibility: because each list element is a full structure containing both data and type information, the list can be filled with data of any desired type. Fixed-type NumPy-style arrays lack this flexibil‐ ity, but are much more efficient for storing and manipulating data. 

# CREATING ARRAYS FROM PYTHON LIST

In [ ]:
import numpy as np 

In [ ]:
np.array([1, 4, 2, 5, 3]) 

array([1, 4, 2, 5, 3])

First, we can use np.array to create arrays from Python lists: 

Remember that unlike Python lists, NumPy is constrained to arrays that all contain the same type. If types do not match, NumPy will upcast if possible (here, integers are upcast to floating point): In[9]: np.array([3.14, 4, 2, 3]) Out[9]: array([ 3.14,  4.  ,  2.  ,  3.  ]) If we want to explicitly set the data type of the resulting array, we can use the dtype keyword: 


In [ ]:
np.array([1, 2, 3, 4], dtype='float32') 

array([1., 2., 3., 4.], dtype=float32)

Finally, unlike Python lists, NumPy arrays can explicitly be multidimensional; here’s one way of initializing a multidimensional array using a list of lists: 

In [ ]:
 #nested lists result in multidimensional arrays
 np.array([range(i, i + 3) for i in [2, 4, 6]]) 

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

# CREATING ARRAYS FROM SCRATCH

Especially for larger arrays, it is more efficient to create arrays from scratch using rou‐ tines built into NumPy. Here are several examples: 

In [ ]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
 # Create a 3x5 floating-point array filled with 1's
 np.ones((3, 5), dtype=float) 

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
 # Create a 3x5 array filled with 3.14
 np.full((3, 5), 3.14) 

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [ ]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2) 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
 # Create an array of five values evenly spaced between 0 and 1
 np.linspace(0, 1, 5) 

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 3)) 

array([[0.83006796, 0.10307214, 0.35491037],
       [0.85657268, 0.75302531, 0.18588834],
       [0.4136854 , 0.48572466, 0.4994994 ]])

In [ ]:
 # Create a 3x3 array of normally distributed random values
 # with mean 0 and standard deviation 1
 np.random.normal(0, 1, (3, 3)) 

array([[ 1.18686153e+00, -1.63161681e+00,  8.34514464e-01],
       [-1.12880018e-01,  6.02276598e-01,  1.64863722e+00],
       [-2.11898358e+00,  1.30231828e-03,  3.47256181e-01]])

In [ ]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3)) 

array([[5, 1, 8],
       [5, 5, 3],
       [2, 4, 5]])

In [ ]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that
# memory location
np.empty(3) 

array([1., 1., 1.])

# The Basics of NumPy Arrays

We’ll cover a few categories of basic array manipulations here: 
 

1. Attributes of arrays Determining the size, shape, memorY consumption, and data types of arrays
2.  Indexing of arrays Getting and setting the value of individual array elements 


 
3.  Slicing of arrays Getting and setting smaller subarrays within a larger array

4. Reshaping of arrays Changing the shape of a given array 

5.   Joining and splitting of arrays Combining multiple arrays into one, and splitting one array into many  
 




**NumPy Array Attributes**

In [ ]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array 

Each array has attributes ndim  (the number of dimensions), shape  (the size of each dimension), and size (the total size of the array): 

In [ ]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size) 

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [ ]:
 print("dtype:", x3.dtype) 

dtype: int64


Other attributes include itemsize, which lists the size (in bytes) of each array ele‐ ment, and nbytes, which lists the total size (in bytes) of the array: 

In [ ]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes") 

itemsize: 8 bytes
nbytes: 480 bytes


**Array Indexing: Accessing Single Elements**

In [ ]:
x1 

array([5, 0, 3, 3, 7, 9])

In [ ]:
x1[0]

5

In [ ]:
x1[4] 

7

In [ ]:
x1[-1] 

9

In [ ]:
x1[-2] 

7

In [ ]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [ ]:
x2[0, 0] 

3

In [ ]:
x2[0, 0] 

3

In [ ]:
x2[2, -1] 

7

In [ ]:
x2[0, 0] = 12
x2 

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [ ]:
In[15]: x1[0] = 3.14159  # this will be truncated!
x1 

array([5, 0, 3, 3, 7, 9])

Keep in mind that, unlike Python lists, NumPy arrays have a fixed type. This means, for example, that if you attempt to insert a floating-point value to an integer array, the value will be silently truncated. Don’t be caught unaware by this behavior! 

**Array Slicing: Accessing Subarrays** 

Just as we can use square brackets to access individual array elements, we can also use them to access subarrays with the slice  notation, marked by the colon (:) character. The NumPy slicing syntax follows that of the standard Python list; to access a slice of an array x, use this:
 
 x[start:stop:step]
 
  If any of these are unspecified, they default to the values start=0, stop=size of dimension, step=1. We’ll take a look at accessing subarrays in one dimension and in multiple dimensions. 
  
  **One-dimensional subarrays** 

In [ ]:
x = np.arange(10)
x 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x[:5]  # first five elements 

array([0, 1, 2, 3, 4])

In [ ]:
x[4:7]  # middle subarray 

array([4, 5, 6])

In [ ]:
x[::2]  # every other element 

array([0, 2, 4, 6, 8])

In [ ]:
x[1::2]  # every other element, starting at index 1 

array([1, 3, 5, 7, 9])

A potentially confusing case is when the step  value is negative. In this case, the defaults for start  and stop  are swapped. This becomes a convenient way to reverse an array: 



In [ ]:
x[::-1]  # all elements, reversed 

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [ ]:
x[5::-2]  # reversed every other from index 5 

array([5, 3, 1])

**Multidimensional subarrays**

 Multidimensional slices work in the same way, with multiple slices separated by com‐ mas. For example: 

In [ ]:
x2 

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [ ]:
x2[:2, :3]  # two rows, three columns 

array([[12,  5,  2],
       [ 7,  6,  8]])

In [ ]:
x2[:3, ::2]  # all rows, every other column 

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

Finally, subarray dimensions can even be reversed together: 

In [ ]:
x2[::-1, ::-1] 

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

Accessing array rows and columns.     One commonly needed routine is accessing single rows or columns of an array. You can do this by combining indexing and slicing, using an empty slice marked by a single colon (:): 

In [ ]:
print(x2[:, 0])  # first column of x2 

[12  7  1]


In [ ]:
print(x2[0, :])  # first row of x2 

[12  5  2  4]


In [ ]:
print(x2[0])  # equivalent to x2[0, :] 

[12  5  2  4]


**Subarrays as no-copy views**

 One important—and extremely useful—thing to know about array slices is that they return views  rather than copies  of the array data. This is one area in which NumPy array slicing differs from Python list slicing: in lists, slices will be copies. Consider our two-dimensional array from before: 

In [ ]:
print(x2) 

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [ ]:
x2_sub = x2[:2, :2]
print(x2_sub) 

[[12  5]
 [ 7  6]]


Now if we modify this subarray, we’ll see that the original array is changed! Observe: I

In [ ]:
x2_sub[0, 0] = 99
print(x2_sub)

[[99  5]
 [ 7  6]]


In [ ]:
print(x2) 

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


This default behavior is actually quite useful: it means that when we work with large datasets, we can access and process pieces of these datasets without the need to copy the underlying data buffer. Creating copies of arrays Despite the nice features of array views, it is sometimes useful to instead explicitly copy the data within an array or a subarray. This can be most easily done with the copy() method: 

In [ ]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy) 

[[99  5]
 [ 7  6]]


In [ ]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy) 

[[42  5]
 [ 7  6]]


**Reshaping of Arrays**


 Another useful type of operation is reshaping of arrays. The most flexible way of doing this is with the reshape()  method. For example, if you want to put the num‐ bers 1 through 9 in a 3×3 grid, you can do the following: 

In [ ]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid) 

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
x = np.array([1, 2, 3])

In [ ]:
x.reshape((1, 3))  

array([[1, 2, 3]])

In [ ]:
x[np.newaxis, :]

array([[1, 2, 3]])

In [ ]:
# column vector via reshape
x.reshape((3, 1)) 

array([[1],
       [2],
       [3]])

In [ ]:
# column vector via newaxis
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

# Array Concatenation and splitting

All of the preceding routines worked on single arrays. It’s also possible to combine multiple arrays into one, and to conversely split a single array into multiple arrays. We’ll take a look at those operations here. 

Concatenation of arrays Concatenation, or joining of two arrays in NumPy, is primarily accomplished through the routines np.concatenate, np.vstack, and np.hstack. np.concatenate takes a tuple or list of arrays as its first argument, as we can see here: 

In [ ]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y]) 

array([1, 2, 3, 3, 2, 1])

In [ ]:
z = [99, 99, 99]

In [ ]:
print(np.concatenate([x, y, z])) 

[ 1  2  3  3  2  1 99 99 99]


In [ ]:
grid = np.array([[1, 2, 3],[4, 5, 6]]) 

In [ ]:
# concatenate along the first axis
np.concatenate([grid, grid]) 

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [ ]:
 # concatenate along the second axis (zero-indexed)
 np.concatenate([grid, grid], axis=1) 

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

For working with arrays of mixed dimensions, it can be clearer to use the np.vstack (vertical stack) and np.hstack (horizontal stack) functions: 



```
# This is formatted as code
```

Splitting of arrays The opposite of concatenation is splitting, which is implemented by the functions np.split, np.hsplit, and np.vsplit. For each of these, we can pass a list of indices giving the split points: 

In [ ]:
from numpy import *